export const actionTypes = {
  SET_CAROUSEL: "SET_CAROUSEL",
  GET_MOVIE_LIST_API: "GET_CAROUSEL_API",
  SET_MOVIE_LIST: "SET_MOVIE_LIST",
  SET_MOVIE_LIST_SEARCH: "SET_MOVIE_LIST_SEARCH",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  SET_HE_THONG_RAP: "SET_HE_THONG_RAP",
  SET__MOVIE_DETAILS: "SET__MOVIE_DETAILS",
  SET_USER: "SET_USER",
  SET_THONG_TIN_PHONG_VE: "SET_THONG_TIN_PHONG_VE",
};
